### ISSUE TITLE
Graph for multiple searches

### ISSUE THREAD

**Issue by rag594** [shakdwipeea/CXLA#10]

**Comment by rag594** [comment]
conflict in the timestamp for different log files

**Comment by shakdwipeea** [comment]
Highlighting the timestamp for each log file may be considered. Then we will have to generate regexp for those dynamically. We could face the following problem

If say the timestamp is `current time is Dec 21, Tue 12:00` then the strings _current_ , _time_ and _is_ should be constant as those are not going to change but _Dec_ and _Tue_ may vary over different logs. So these should be kept into account.

@rag594 Do u have anything in mind for this?

**Comment by rag594** [comment]
@shakdwipeea For now it is sufficient

**Comment by rag594** [comment]
@shakdwipeea UI is left
