### ISSUE TITLE
Use template-literal instead of EJS

### ISSUE THREAD

**Issue by Drulac** [shakdwipeea/CXLA#30]
[Template Literal](https://github.com/Drulac/template-literal) is fastest, smallest and simplest template engine, because it use JS's literal template feature.

It's  55 times faster than EJS, and it also use less CPU and RAM ressources, so it may be a good idea to use it instead of EJS 😀

**Comment by shakdwipeea** [comment]
@Drulac it looks like an interesting library, will definitely check it out. 
However in this project, most of our templating work is being done by handlebars and raw js. Most of our templates are simple and we have not faced any performance bottlenecks wrt this.
